version: '3'
services:
  speedwagon:
    image: envoyproxy/envoy-alpine:v1.17-latest
    volumes:
      - ./proxy/envoy-dev.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - 5001:5001
      - 9901:9901
