version: '3.8'
services:
  doppio:
    image: "ghcr.io/pascalhonegger/cc-doppio"
    networks:
      - speedwagon_net

  speedwagon:
    image: envoyproxy/envoy-alpine:v1.17-latest
    networks:
      - speedwagon_net

  joestar:
    image: "ghcr.io/pascalhonegger/cc-joestar"
    environment:
      JOESTAR_PORT: 8080
      ROHAN_SERVER: rohan
      ROHAN_PORT: 9090
    networks:
      - speedwagon_net
      - rohan_net

  rohan:
    image: "ghcr.io/pascalhonegger/cc-rohan"
    networks:
      - rohan_net
    environment:
      ROHAN_PORT: 9090
