version: '3'
services:
  doppio:
    image: "ghcr.io/pascalhonegger/cc-doppio"
    restart: unless-stopped
    networks:
      - speedwagon_net

  speedwagon:
    image: "ghcr.io/pascalhonegger/cc-speedwagon"
    restart: unless-stopped
    volumes:
      - ./certs:/etc/envoy/certs:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - speedwagon_net

  joestar:
    image: "ghcr.io/pascalhonegger/cc-joestar"
    restart: unless-stopped
    environment:
      ROHAN_SERVER: rohan
      JWT_SECRET: base-64-encoded-512-bit-key
    networks:
      - speedwagon_net
      - rohan_net

  rohan:
    image: "ghcr.io/pascalhonegger/cc-rohan"
    restart: unless-stopped
    networks:
      - rohan_net

networks:
  speedwagon_net:
    name: speedwagon_net
  rohan_net:
    name: rohan_net
