version: '3.3'
services:
  doppio:
    extends:
      file: docker-compose.yml
      service: doppio
    build:
      context: ./frontend

  speedwagon:
    extends:
      file: docker-compose.yml
      service: speedwagon
    build:
      context: ./backend
      dockerfile: Dockerfile.speedwagon
    ports:
      - 9901:9901

  joestar:
    extends:
      file: docker-compose.yml
      service: joestar
    build:
      context: ./backend
      dockerfile: Dockerfile.joestar
    environment:
      JWT_SECRET: kiMu3ODiG8NdA41/6bj5BcsKDUplTh32bmocO3EKbgbOdHGBfST1/dtfuh+hMOTqEGurJgMPI0XCUewlBWEdrw==

  rohan:
    extends:
      file: docker-compose.yml
      service: rohan
    build:
      context: ./backend
      dockerfile: Dockerfile.rohan

networks:
  speedwagon_net:
    name: speedwagon_net
  rohan_net:
    name: rohan_net
