version: '3.8'
services:
  doppio:
    extends:
      file: docker-compose.common.yml
      service: doppio

  speedwagon:
    extends:
      file: docker-compose.common.yml
      service: speedwagon
    volumes:
      - ./backend/envoy-prod.yaml:/etc/envoy/envoy.yaml:ro
      - ./certs:/etc/envoy/certs:ro
    ports:
      - 80:80
      - 443:443

  joestar:
    extends:
      file: docker-compose.common.yml
      service: joestar

  rohan:
    extends:
      file: docker-compose.common.yml
      service: rohan
