version: '3.3'
services:
  doppio:
    extends:
      file: docker-compose.common.yml
      service: doppio

  speedwagon:
    extends:
      file: docker-compose.common.yml
      service: speedwagon

  joestar:
    extends:
      file: docker-compose.common.yml
      service: joestar

  rohan:
    extends:
      file: docker-compose.common.yml
      service: rohan

networks:
  speedwagon_net:
    name: speedwagon_net
  rohan_net:
    name: rohan_net
