version: '3.8'
services:
  speedwagon:
    image: envoyproxy/envoy-alpine:v1.17-latest
    volumes:
      - ./backend/envoy-dev.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - 5001:5001
      - 9901:9901
# Required on Linux
#    extra_hosts:
#      - "host.docker.internal:host-gateway"