version: '3'
services:
  speedwagon:
    image: "ghcr.io/pascalhonegger/cc-speedwagon"
    build:
      context: ./proxy
    volumes:
      - ./proxy/envoy-dev.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - 5001:5001
      - 9901:9901
