version: '3.8'
services:
  gen_grpc_joestar_client:
    image: namely/protoc-all
    volumes:
      - "./backend/grpc/joestar:/defs"
      - "./frontend/src/gen:/generated"
    command: -o /generated -d /defs -l web --grpc-web-out=import_style=typescript,mode=grpcweb:/generated
