version: '3.8'
services:
  doppio:
    extends:
      file: docker-compose.common.yml
      service: doppio
    build:
      context: ./frontend
      dockerfile: Dockerfile

  speedwagon:
    extends:
      file: docker-compose.common.yml
      service: speedwagon
    volumes:
      - ./backend/envoy-prod.yaml:/etc/envoy/envoy.yaml

  joestar:
    extends:
      file: docker-compose.common.yml
      service: joestar
    build:
      context: ./backend
      dockerfile: Dockerfile.joestar

  rohan:
    extends:
      file: docker-compose.common.yml
      service: rohan
    build:
      context: ./backend
      dockerfile: Dockerfile.rohan

networks:
  speedwagon_net:
    name: speedwagon_net
  rohan_net:
    name: rohan_net