FROM gradle:jdk15 as build

COPY . .
RUN gradle :rohan:shadowjar --no-daemon

FROM openjdk:15-jdk-alpine
VOLUME /etc/rohan/
COPY --from=build /home/gradle/rohan/build/libs/rohan-*-all.jar /rohan.jar
ENTRYPOINT ["java","-jar","/rohan.jar"]
