FROM gradle:jdk15 as build

COPY . .
RUN gradle :joestar:shadowjar --no-daemon

FROM openjdk:15-jdk-alpine
COPY --from=build /home/gradle/joestar/build/libs/joestar-*-all.jar /joestar.jar
ENTRYPOINT ["java","-jar","/joestar.jar"]
