FROM gradle:jdk15 as build

COPY . .
RUN gradle :rohan:shadowjar --no-daemon

FROM adoptopenjdk:15-jre-hotspot
VOLUME /etc/rohan/
COPY --from=build /home/gradle/rohan/build/libs/rohan-*-all.jar /rohan.jar
HEALTHCHECK --interval=10s --timeout=5s --retries=5 --start-period=3s \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8086/health/liveness || exit 1
ENTRYPOINT ["java","-jar","/rohan.jar"]
