micronaut:
  application:
    name: joestar
grpc:
  server:
    port: '${joestar.port:`80`}'
  channels:
    rohan:
      address: '${rohan.server:`localhost`}:${rohan.port:`80`}'
      plaintext: true