micronaut:
  application:
    name: joestar
  server:
    port: 8086
grpc:
  server:
    port: '${joestar.port:`8081`}'
  channels:
    rohan:
      address: '${rohan.server:`localhost`}:${rohan.port:`9091`}'
      plaintext: true
endpoints:
  all:
    enabled: false
  health:
    details-visible: anonymous
    enabled: true
    sensitive: false
    disk-space:
      enabled: false
jwt:
  issuer: Joestar
  audience: Doppio
  clock-skew: 1m
  valid-for: 7d
