micronaut:
  application:
    name: joestar
grpc:
  server:
    port: '${joestar.port:`8081`}'
  channels:
    rohan:
      address: '${rohan.server:`localhost`}:${rohan.port:`9091`}'
      plaintext: true
